export enum ClientEvents {
  ROOMS_LIST = "ROOMS_LIST",
  JOIN_GAME = "JOIN_GAME",
  CREATE_GAME = "CREATE_GAME",
  MESSAGE = "MESSAGE",
  COMMAND = "COMMAND",
  START_GAME = "GAME_STATE",
  GIVE_UP = "GIVE_UP",
}
