export enum ServerEvents {
  ROOMS_LIST = "ROOMS_LIST",
  USER_JOINED = "USER_JOINED",
  CREATED_ROOM = "CREATED_ROOM",
  ERROR = "ERROR",
  GAME_STARTED = "GAME_STARTED",
  MESSAGE = "MESSAGE",
  MOVE = "MOVE",
  INITIAL_GAME_CONFIG = "GAME_STATE",
  PLAYER_WON = "USER_WON",
  USER_TURN = "USER_TURN",
  USER_GAVE_UP = "USER_GAVE_UP",
}
