export enum ServerEvents {
  ROOMS_LIST = 'ROOMS_LIST',
  USER_JOINED = 'USER_JOINED',
  ERROR = 'ERROR',
  CREATED_ROOM = 'CREATED_ROOM',
  GAME_STARTED = 'GAME_STARTED',
  MESSAGE = 'MESSAGE',
  MOVE = 'MOVE',
  GAME_STATE = 'GAME_STATE',
  USER_WON = 'USER_WON',
  USER_TURN = 'USER_TURN',
  USER_GAVE_UP = 'USER_GAVE_UP',
}
